admin_index:
    pattern: /admin/
    defaults: { _controller: AdminBundle:Default:index }
    
AdminBundle_profesor:
        resource: "@AdminBundle/Resources/config/routing/profesor.yml"
        prefix:   /profesor

Admin_show_archivo:
    pattern: /admin/show/{id}
    defaults: { _controller: AdminBundle:Archivo:show }
