admin_index:
    pattern: /admin
    defaults: { _controller: 'AdminBundle:Default:index' }

AdminBundle_profesor:
        resource: "@AdminBundle/Resources/config/routing/profesor.yml"
        prefix:   /profesor

AdminBundle_informe:
        resource: "@AdminBundle/Resources/config/routing/informe.yml"
        prefix:   /informe
