admin_index:
    pattern: /home
    defaults: { _controller: 'AdminBundle:Default:index' }

AdminBundle_profesor:
        resource: "@AdminBundle/Resources/config/routing/profesor.yml"
        prefix:   /administradores

AdminBundle_informe:
        resource: "@AdminBundle/Resources/config/routing/informe.yml"
        prefix:   /informes

AdminBundle_juego:
        resource: "@AdminBundle/Resources/config/routing/juego.yml"
        prefix:   /juegos


        
puntuaciones:
    pattern: /puntuaciones/{id}
    defaults: { _controller: 'AdminBundle:Puntuaciones:show' }
    
grafica:
    pattern: /grafica/{div}/{id}/{dificultad}
    defaults: { _controller: 'AdminBundle:Grafica:DrawChart' }
    
grafica_index:
    pattern: /grafica/indice
    defaults: { _controller: 'AdminBundle:Grafica:indice' }