admin_index:
    pattern: /admin
    defaults: { _controller: 'AdminBundle:Default:index' }

AdminBundle_profesor:
        resource: "@AdminBundle/Resources/config/routing/profesor.yml"
        prefix:   /profesor

AdminBundle_informe:
        resource: "@AdminBundle/Resources/config/routing/informe.yml"
        prefix:   /informe
        
puntuaciones:
    pattern: /puntuaciones/{id}
    defaults: { _controller: 'AdminBundle:Puntuaciones:show' }
    
grafica:
    pattern: /grafica
    defaults: { _controller: 'AdminBundle:Grafica:chart' }
    
grafica_index:
    pattern: /grafica/indice
    defaults: { _controller: 'AdminBundle:Grafica:indice' }