parameters:
#    admin.example.class: Edukagames\AdminBundle\Example

services:
#    admin.example:
#        class: %admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
