login:
    pattern: /
    defaults: { _controller: 'UserBundle:Default:login' }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

#pagina principal de alumno
user_index:
    pattern: /usuario
    defaults: { _controller: 'UserBundle:Default:index'}
#   

UserBundle_alumno:
    resource: "@UserBundle/Resources/config/routing/alumno.yml"
    prefix: /alumno



    
alumnos_details:
    pattern: /admin/{id}
    defaults: { _controller: 'UserBundle:Alumno:AlumnoDetails' }