login:
    pattern: /
    defaults: { _controller: UserBundle:Default:login }
 
login_check:
    pattern: /login_check
 
logout:
    pattern: /logout

user_index:
    pattern: /usuario
    defaults: { _controller: UserBundle:Default:index }
    
user_perfil_edit:
    pattern: /usuario/profile
    defaults: { _controller: UserBundle:Default:perfil }