parameters:
#    user.example.class: Edukagames\UserBundle\Example

services:
    # user.example:
    # class: %user.example.class%
    # arguments: [@service_id, "plain_value", %parameter%]
    login_listener:
        class: Edukagames\UserBundle\Listener\LoginListener
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login}
            - { name: kernel.event_listener, event: kernel.response }