jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Edukagames\UserBundle\Entity\Alumno: plaintext
        Edukagames\AdminBundle\Entity\Profesor: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [alumno, profesor]
        alumno:
            entity: { class: Edukagames\UserBundle\Entity\Alumno, property: userName }
        profesor:
            entity: { class: Edukagames\AdminBundle\Entity\Profesor, property: nombre }

    firewalls:
        login_user:
            pattern: ^/*
            anonymous: ~
            form_login:
                provider: chain_provider    
                login_path: /
                check_path: /login_check
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
