security:
    encoders:
        Edukagames\UserBundle\Entity\Alumno: { algorithm: md5, iterations: 1,  encode-as-base64: false }
        Edukagames\AdminBundle\Entity\Profesor: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        
    providers:
        chain_provider:
            chain:
                providers: [alumno, profesor]
        alumno:
            entity: { class: Edukagames\UserBundle\Entity\Alumno, property: userName }
        profesor:
            entity: { class: Edukagames\AdminBundle\Entity\Profesor, property: nombre }

    firewalls:
        login_user:
            pattern: ^/
#            anonymous: ~
            form_login:
                provider: chain_provider
                always_use_default_target_path: true
                default_target_path: /usuario   
                login_path: /
                check_path: /login_check
            logout:
                path: /logout
                target: /
            security: true
            anonymous: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
#        - { path: /usuario, roles: ROLE_USER }
#        - { path: /admin, roles: ROLE_ADMIN }
#        - { path: %kernel.root_dir%/../web/, roles: ROLE_USER }
#        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /user/profile, roles: ROLE_ADMIN }
#        - { path: /.*, roles: ROLE_ADMIN }
