informe:
    pattern:  /{id}
    defaults: { _controller: "AdminBundle:Informe:index", count: -1 }

informe_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Informe:show" }

informe_new:
    pattern:  /new/{id}
    defaults: { _controller: "AdminBundle:Informe:new" }

informe_create:
    pattern:  /create/{id}
    defaults: { _controller: "AdminBundle:Informe:create" }
    requirements: { _method: post }

informe_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Informe:edit" }

informe_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Informe:update" }

informe_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Informe:delete" }

